-- POPULATING DATA

-- TABLE_BRANCH

INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Market', 'Edinburgh', 'EH1 5AB', '901', table_Phone_nested(type_Phone('bPhone', '01311235560')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Knight', 'Aberdeen', 'AB3 37H', '902', table_Phone_nested(type_Phone('bPhone', '01987889955')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Pawn', 'Newcastle', 'YN8 9HV', '903', table_Phone_nested(type_Phone('bPhone', '01123678945')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Queen', 'Dunfermline', 'KY11 1HY', '904', table_Phone_nested(type_Phone('bPhone', '01383224477')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Princes St', 'Edinburgh', 'EH4 8HY', '905', table_Phone_nested(type_Phone('bPhone', '01311235580')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Kings', 'London', 'N1C 3AF', '906', table_Phone_nested(type_Phone('bPhone', '0171543214')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Cross', 'London', 'N7C 7BD', '907', table_Phone_nested(type_Phone('bPhone', '0171345670')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Bridge', 'Glasgow', 'G18 1QQ', '908', table_Phone_nested(type_Phone('bPhone', '01413214556')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Buccleugh', 'Glasgow', 'G2P BDV', '909', table_Phone_nested(type_Phone('bPhone', '0123456789')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('George St', 'Edinburgh', 'EH4 6YG', '910', table_Phone_nested(type_Phone('bPhone', '0131345678')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Chelsea', 'London', 'N8C 0LN', '911', table_Phone_nested(type_Phone('bPhone', '01716985632')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Bishop', 'York', 'DN3 6YT', '912', table_Phone_nested(type_Phone('bPhone', '01567223344')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Dairy', 'Manchester', 'MH3 9IF', '913', table_Phone_nested(type_Phone('bPhone', '01987645231')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Milk', 'London', 'NV5 9GH', '914', table_Phone_nested(type_Phone('bPhone', '012789765490')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Crunchie', 'Cardiff', 'C0A BNA', '915', table_Phone_nested(type_Phone('bPhone', '01897634367')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Galaxy', 'Dundee', 'DN9 1XC', '916', table_Phone_nested(type_Phone('bPhone', '01678458392')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Rook', 'Hull', 'HN5 9GD', '917', table_Phone_nested(type_Phone('bPhone', '01234987654')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Roses', 'Dunfermline', 'KY12 4JD', '918', table_Phone_nested(type_Phone('bPhone', '01678453627')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Terrys', 'Newcastle', 'NK5 6GD', '919', table_Phone_nested(type_Phone('bPhone', '01345894638')));
INSERT INTO table_branch (street, city, postCode, bID, phone) VALUES ('Bear', 'London', 'N6U 9QW', '920', table_Phone_nested(type_Phone('bPhone', '01567894321')));

-- TABLE_ACCOUNT

INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1001', 'current', '820.50', (SELECT REF(b) FROM table_branch b WHERE b.bID = '901'), '0.005', '800', to_date('2016-05-01','yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1010', 'savings', '3122.20', (SELECT REF(b) FROM table_branch b WHERE b.bID = '905'), '0.02', '0', to_date('2015-05-08', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1002', 'current', '200', (SELECT REF(b) FROM table_branch b WHERE b.bID = '909'), '0.005', '100', to_date('2012-05-05', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1040', 'current', '159.65', (SELECT REF(b) FROM table_branch b WHERE b.bID = '905'), '0.01', '250', to_date('2010-07-02', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1220', 'savings', '12001.76', (SELECT REF(b) FROM table_branch b WHERE b.bID = '910'), '0.005', '0', to_date('2012-08-13', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1065', 'current', '48.61', (SELECT REF(b) FROM table_branch b WHERE b.bID = '905'), '0.08', '500', to_date('2015-09-30', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1495', 'savings', '567.01', (SELECT REF(b) FROM table_branch b WHERE b.bID = '901'), '0.01', '0', to_date('2015-06-20', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1055', 'savings', '25604.24', (SELECT REF(b) FROM table_branch b WHERE b.bID = '920'), '0.05', '0', to_date('2018-01-06', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1016', 'savings', '13334.02', (SELECT REF(b) FROM table_branch b WHERE b.bID = '910'), '0.001', '0', to_date('2017-12-12', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1134', 'current', '675.75', (SELECT REF(b) FROM table_branch b WHERE b.bID = '909'), '0.02', '325', to_date('2014-09-04', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1111', 'current', '768.01', (SELECT REF(b) FROM table_branch b WHERE b.bID = '901'), '0.009', '1000', to_date('2013-02-06', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1798', 'savings', '8945.89', (SELECT REF(b) FROM table_branch b WHERE b.bID = '905'), '0.01', '0', to_date('2009-07-31', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1628', 'savings', '14555.09', (SELECT REF(b) FROM table_branch b WHERE b.bID = '911'), '0.006', '0', to_date('2007-06-23', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1389', 'savings', '4679.53', (SELECT REF(b) FROM table_branch b WHERE b.bID = '910'), '0.03', '0', to_date('2013-09-29', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1786', 'current', '7056.98', (SELECT REF(b) FROM table_branch b WHERE b.bID = '911'), '0.09', '300', to_date('2018-09-25', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1342', 'savings', '13567.05', (SELECT REF(b) FROM table_branch b WHERE b.bID = '910'), '0.07', '0', to_date('2020-01-03', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1019', 'current', '658.87', (SELECT REF(b) FROM table_branch b WHERE b.bID = '908'), '0.02', '750', to_date('2008-03-03', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1689', 'savings', '7654.98', (SELECT REF(b) FROM table_branch b WHERE b.bID = '905'), '0.007', '0', to_date('2014-12-14', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1345', 'current', '9080.78', (SELECT REF(b) FROM table_branch b WHERE b.bID = '918'), '0.008', '800', to_date('2015-09-09', 'yyyy-mm-dd'));
INSERT INTO table_account (accNum, accType, balance, bID, inRate, limitOfFreeOD, OpenDate) VALUES ('A1567', 'savings', '12077.90', (SELECT REF(b) FROM table_branch b WHERE b.bID = '907'), '0.002', '0', to_date('2019-08-07', 'yyyy-mm-dd'));

-- TABLE_EMPLOYEE_POSITION

INSERT INTO table_employee_position (jobID, jobTitle, salary) VALUES ('01', 'Head', '50000');
INSERT INTO table_employee_position (jobID, jobTitle, salary) VALUES ('02', 'Manager', '40000');
INSERT INTO table_employee_position (jobID, jobTitle, salary) VALUES ('03', 'Project Leader', '35000');
INSERT INTO table_employee_position (jobID, jobTitle, salary) VALUES ('04', 'Accountant', '30000');
INSERT INTO table_employee_position (jobID, jobTitle, salary) VALUES ('05', 'Cashier', '25000');

-- TABLE_EMPLOYEE

INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Mr', 'Stuart', 'Jones'), type_address('Colinton', 'Edinburgh', 'EH10 5TT'), table_Phone_nested(type_Phone('HomePhone', '01315678904'), type_Phone('Mobile1', '07685675424')), 'HG09864A', 'E101', (SELECT REF(b) FROM table_branch b WHERE b.bID = '901'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '01'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E101'),  to_date('2002-07-07', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Mrs', 'Alison', 'Smith'), type_address('Newton', 'Edinburgh', 'EH12 8TY'), table_Phone_nested(type_Phone('HomePhone', '01319865325'), type_Phone('Mobile1', '0784546474')), 'AX8975B', 'E201', (SELECT REF(b) FROM table_branch b WHERE b.bID = '901'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '02'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E101'),  to_date('2012-07-07', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Miss', 'Stacey', 'Yale'), type_address('Rose', 'Edinburgh', 'EH16 2VC'), table_Phone_nested(type_Phone('HomePhone', '01317354776'), type_Phone('Mobile1', '0776532465')), 'CV9854Y', 'E301', (SELECT REF(b) FROM table_branch b WHERE b.bID = '901'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '03'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E201'),  to_date('2013-07-17', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Mr', 'Homer', 'Simpson'), type_address('Carlton', 'Peniculk', 'PC7 8TD'), table_Phone_nested(type_Phone('HomePhone', '01456789754'), type_Phone('Mobile1', '0786534579')), 'BH6786A', 'E302', (SELECT REF(b) FROM table_branch b WHERE b.bID = '901'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '03'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E201'),  to_date('2020-10-16', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Ms', 'Margaret', 'Brown'), type_address('Tree', 'Livingston', 'LN6 2VC'), table_Phone_nested(type_Phone('HomePhone', '018754638398'), type_Phone('Mobile1', '0764356789')), 'WQ0976U', 'E401', (SELECT REF(b) FROM table_branch b WHERE b.bID = '901'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '04'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E302'),  to_date('2002-07-07', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Mr', 'Stanley', 'Burns'), type_address('Sugar', 'Edinburgh', 'EH79UR'), table_Phone_nested(type_Phone('HomePhone', '01345967899'), type_Phone('Mobile1', '0777613468')), 'YU0927Y', 'E501', (SELECT REF(b) FROM table_branch b WHERE b.bID = '901'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '05'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E301'),  to_date('2017-03-23', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Mr', 'David', 'Bird'), type_address('Hyde', 'Edinburgh', 'EH0 0TY'), table_Phone_nested(type_Phone('HomePhone', '01345654332'), type_Phone('Mobile1', '0775439202')), 'IT0987B', 'E502', (SELECT REF(b) FROM table_branch b WHERE b.bID = '901'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '05'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E301'),  to_date('2010-08-14', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Miss', 'Joanna', 'Robinson'), type_address('Wood', 'Glasgow', 'GW9 0BH'), table_Phone_nested(type_Phone('HomePhone', '0156786456'), type_Phone('Mobile1', '0786432977')), 'LK9876F', 'E102', (SELECT REF(b) FROM table_branch b WHERE b.bID = '908'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '01'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E102'),  to_date('2015-12-15', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Mr', 'John', 'Paterson'), type_address('Ruby', 'Cumbernauld', 'GO10 8RE'), table_Phone_nested(type_Phone('HomePhone', '01678654321'), type_Phone('Mobile1', '0776536789')), 'YT0986P', 'E202', (SELECT REF(b) FROM table_branch b WHERE b.bID = '908'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '02'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E102'),  to_date('2014-09-09', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Ms', 'Rose', 'Tate'), type_address('Garnet', 'Glasgow', 'GP0 3FA'), table_Phone_nested(type_Phone('HomePhone', '01389987643'), type_Phone('Mobile1', '0765467890')), 'GH8798K', 'E303', (SELECT REF(b) FROM table_branch b WHERE b.bID = '908'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '03'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E202'),  to_date('2008-07-04', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Miss', 'Lauren', 'Noble'), type_address('Brown', 'Glasgow', 'GT9 9OU'), table_Phone_nested(type_Phone('HomePhone', '01567985493'), type_Phone('Mobile1', '0797636780')), 'TQ0989Q', 'E402', (SELECT REF(b) FROM table_branch b WHERE b.bID = '908'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '04'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E303'),  to_date('2009-09-14', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Mrs', 'Samantha', 'Brown'), type_address('Abbotsford', 'Glasgow', 'GY10 8YE'), table_Phone_nested(type_Phone('HomePhone', '01678957345'), type_Phone('Mobile1', '0765263748')), 'UI9564U', 'E503', (SELECT REF(b) FROM table_branch b WHERE b.bID = '908'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '05'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E303'),  to_date('2002-04-25', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Miss', 'Katy', 'Grant'), type_address('Eildon', 'Glasgow', 'GW11 5RE'), table_Phone_nested(type_Phone('HomePhone', '0176536383'), type_Phone('Mobile1', '0765649890')), 'EW0987P', 'E504', (SELECT REF(b) FROM table_branch b WHERE b.bID = '908'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '05'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E303'),  to_date('2019-02-28', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Mr', 'Peter', 'Anderson'), type_address('Pearl', 'London', 'NP7 7YU'), table_Phone_nested(type_Phone('HomePhone', '01456748393'), type_Phone('Mobile1', '07646373839')), 'HY6789I', 'E103', (SELECT REF(b) FROM table_branch b WHERE b.bID = '920'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '01'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E103'),  to_date('2010-08-14', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Mr', 'Daniel', 'Bell'), type_address('Hyde', 'London', 'NO0 0TY'), table_Phone_nested(type_Phone('HomePhone', '01345654332'), type_Phone('Mobile1', '07856474899')), 'XC0987A', 'E203', (SELECT REF(b) FROM table_branch b WHERE b.bID = '920'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '02'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E103'),  to_date('2010-08-14', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Mr', 'Aaron', 'Johnson'), type_address('Park', 'London', 'NQ12 3LO'), table_Phone_nested(type_Phone('HomePhone', '0185677998'), type_Phone('Mobile1', '0763526890')), 'LK8573P', 'E304', (SELECT REF(b) FROM table_branch b WHERE b.bID = '920'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '03'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E203'),  to_date('2018-02-19', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Mrs', 'Helen', 'Bryll'), type_address('Jekyll', 'London', 'ND7 9OY'), table_Phone_nested(type_Phone('HomePhone', '01597738393'), type_Phone('Mobile1', '0756373839')), 'AS0973U', 'E305', (SELECT REF(b) FROM table_branch b WHERE b.bID = '920'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '03'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E203'),  to_date('2016-07-03', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Ms', 'Kristen', 'Dance'), type_address('Square', 'London', 'NP10 6RW'), table_Phone_nested(type_Phone('HomePhone', '01576373830'), type_Phone('Mobile1', '0736373930')), 'VB6793U', 'E404', (SELECT REF(b) FROM table_branch b WHERE b.bID = '920'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '04'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E303'),  to_date('2018-03-04', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Miss', 'Joyce', 'Pattinson'), type_address('Circus', 'London', 'ND0 8YW'), table_Phone_nested(type_Phone('HomePhone', '0154498438'), type_Phone('Mobile1', '0788877899')), 'BT0987Y', 'E405', (SELECT REF(b) FROM table_branch b WHERE b.bID = '920'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '05'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E303'),  to_date('2010-08-14', 'yyyy-mm-dd'));
INSERT INTO table_employee (name, address, phone, niNum, empID, bID, position, supervisorID, joinDate) VALUES (type_name('Mrs', 'Bella', 'Scott'), type_address('Tree', 'London', 'NY7 5RW'), table_Phone_nested(type_Phone('HomePhone', '01524097362'), type_Phone('Mobile1', '0783876287')), 'XP0972V', 'E505', (SELECT REF(b) FROM table_branch b WHERE b.bID = '920'), (SELECT REF(p) FROM table_employee_position p WHERE p.jobID = '05'), (SELECT REF(s) FROM table_employee s WHERE s.empID='E203'),  to_date('2017-07-23', 'yyyy-mm-dd'));


-- TABLE_CUSTOMER

INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Miss', 'Becky', 'Tate'), type_address('Bridge', 'Edinburgh', 'EH10 3YT'), table_Phone_nested(type_Phone('HomePhone', '0134566362'), type_Phone('Mobile1', '0783876287'), type_Phone('Mobile2', '07654689066')), 'DR6787U', 'Cust101');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Mr', 'Blair', 'Turnbull'), type_address('Wether', 'Edinburgh', 'EH15 8TY'), table_Phone_nested(type_Phone('HomePhone', '0137654678'), type_Phone('Mobile1', '07654323748'), type_Phone('Mobile2', '076363739303')), 'YA0986T', 'Cust102');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Mrs', 'Jenny', 'Tay'), type_address('Hill', 'Dunfermline', 'KY14 8YE'), table_Phone_nested(type_Phone('Mobile1', '07765425689'), type_Phone('Mobile2', '07504536389')), 'TG5637I', 'Cust103');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Mr', 'Harry', 'Tate'), type_address('Hill', 'Dunfermline', 'KY14 8YE'), table_Phone_nested(type_Phone('Mobile1', '07765425689'), type_Phone('Mobile2', '07624533889')), 'HB0987Y', 'Cust104');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Mr', 'Zach', 'Martin'), type_address('Spoons', 'Rosyth', 'KY13 7YE'), table_Phone_nested(type_Phone('HomePhone', '01345748439'), type_Phone('Mobile1', '07767667766'), type_Phone('Mobile2', '07765655546')), 'QW0987P', 'Cust105');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Miss', 'Jenna', 'Scott'), type_address('Abbeyview', 'Glasgow', 'GWH9 7QE'), table_Phone_nested(type_Phone('HomePhone', '01328736474'), type_Phone('Mobile1', '07504287387'), type_Phone('Mobile2', '07656182829')), 'BZ0956J', 'Cust106');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Ms', 'Jessica', 'Hamilton'), type_address('Brush', 'Glasgow', 'GW98 6EW'), table_Phone_nested(type_Phone('Mobile1', '07505425689'), type_Phone('Mobile2', '07624533889')), 'IJ0975A', 'Cust107');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Mr', 'Arthur', 'Dayne'), type_address('Ring', 'Edinburgh', 'ERT5 8YW'), table_Phone_nested(type_Phone('Mobile1', '07808765435'), type_Phone('Mobile2', '07504554321')), 'LK4321H', 'Cust108');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Mrs', 'Maria', 'Musk'), type_address('Flag', 'London', 'NP8 9IT'), table_Phone_nested(type_Phone('HomePhone', '01787738393'), type_Phone('Mobile1', '07636372829')), 'ZX3957U', 'Cust109');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Mr', 'Richard', 'Armstrong'), type_address('Circle', 'London', 'NU7 9RT'), table_Phone_nested(type_Phone('HomePhone', '01345967439'), type_Phone('Mobile1', '0750940022'), type_Phone('Mobile2', '0764902020')), 'ER0938U', 'Cust110');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Miss', 'Mercedes', 'Wilson'), type_address('Cushion', 'Falkirk', 'FN0 8HD'), table_Phone_nested(type_Phone('HomePhone', '01874938398'), type_Phone('Mobile1', '07738929283')), 'YE0937', 'Cust111');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Mr', 'Jamie', 'Clarke'), type_address('Bottle', 'Edinburgh', 'EH8 9UR'), table_Phone_nested(type_Phone('HomePhone', '0128839838'), type_Phone('Mobile1', '0738393939')), 'HL3856P', 'Cust112');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Mrs', 'Rebecca', 'Button'), type_address('Abbeyroad', 'London', 'NJ6 9JD'), table_Phone_nested(type_Phone('HomePhone', '0145894949'), type_Phone('Mobile1', '0765850505')), 'BC0946D', 'Cust113');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Mr', 'Benjamin', 'Button'), type_address('Abbeyroad', 'London', 'NJ6 9JD'), table_Phone_nested(type_Phone('HomePhone', '0145894949'), type_Phone('Mobile1', '0747484949')), 'AW4555H', 'Cust114');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Ms', 'Rachel', 'Green'), type_address('Market', 'Edinburgh', 'EH5 9GE'), table_Phone_nested(type_Phone('HomePhone', '01478984842'), type_Phone('Mobile1', '0775484930')), 'MC8378H', 'Cust115');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Mr', 'Brian', 'Davis'), type_address('Mirror', 'Dunfermline', 'KY13 9UY'), table_Phone_nested(type_Phone('HomePhone', '0134598679'), type_Phone('Mobile1', '07736297987'), type_Phone('Mobile2', '0750937837')), 'QW0987P', 'Cust121');
-- EMPLOYEES WHO ARE CUSTOMERS
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Mr', 'Stanley', 'Burns'), type_address('Sugar', 'Edinburgh', 'EH79UR'), table_Phone_nested(type_Phone('HomePhone', '01345967899'), type_Phone('Mobile1', '0777613468')), 'YU0927Y', 'Cust116');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Miss', 'Joanna', 'Robinson'), type_address('Wood', 'Glasgow', 'GW9 0BH'), table_Phone_nested(type_Phone('HomePhone', '0156786456'), type_Phone('Mobile1', '0786432977')), 'LK9876F', 'Cust117');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Mr', 'Homer', 'Simpson'), type_address('Carlton', 'Peniculk', 'PC7 8TD'), table_Phone_nested(type_Phone('HomePhone', '01456789754'), type_Phone('Mobile1', '0786534579')), 'BH6786A', 'Cust118');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Mrs', 'Bella', 'Scott'), type_address('Tree', 'London', 'NY7 5RW'), table_Phone_nested(type_Phone('HomePhone', '01524097362'), type_Phone('Mobile1', '0783876287')), 'XP0972V', 'Cust119');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Miss', 'Stacey', 'Yale'), type_address('Rose', 'Edinburgh', 'EH16 2VC'), table_Phone_nested(type_Phone('HomePhone', '01317354776'), type_Phone('Mobile1', '0776532465')), 'CV9854Y', 'Cust120');
INSERT INTO table_customer (name, address, phone, niNum, custID) VALUES (type_name('Ms', 'Rose', 'Tate'), type_address('Garnet', 'Glasgow', 'GP0 3FA'), table_Phone_nested(type_Phone('HomePhone', '01389987643'), type_Phone('Mobile1', '0765467890')), 'GH8798K', 'Cust122');


-- TABLE_CUSTOMER_ACCOUNT
-- SINGLE ACCOUNTS
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust101'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1001'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust102'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1016'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust105'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1798'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust106'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1134'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust107'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1019'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust108'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1495'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust109'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1055'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust110'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1220'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust112'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1389'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust117'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1002'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust118'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1689'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust111'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1342'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust115'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1111'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust122'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1065'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust119'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1628'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust121'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1567'));
-- JOINT CURRENT ACCOUNT
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust103'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1345'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust104'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1345'));
INSERT INTO table_customer_account (custId, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust113'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1786'));
INSERT INTO table_customer_account (custId, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust114'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1786'));
-- MULTIPLE ACCOUNTS
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust116'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1010'));
INSERT INTO table_customer_account (custID, accNum) VALUES ((SELECT REF(c) FROM table_customer c WHERE c.custID = 'Cust116'), (SELECT REF(n) FROM table_account n WHERE n.accNum = 'A1040'));






