--DROP TYPES

DROP TYPE TYPE_ACCOUNT FORCE;
DROP TYPE TYPE_ADDRESS FORCE;
DROP TYPE TYPE_BRANCH FORCE;
DROP TYPE TYPE_CUSTOMER FORCE;
DROP TYPE TYPE_EMPLOYEE FORCE;
DROP TYPE TYPE_NAME FORCE;
DROP TYPE TYPE_PERSON FORCE;
DROP TYPE TYPE_PHONE FORCE;
DROP TYPE TYPE_EMPLOYEE_POSITION FORCE;
DROP TYPE TABLE_PHONE_NESTED FORCE;

--DROP TABLES

DROP TABLE TABLE_ACCOUNT;
DROP TABLE TABLE_EMPLOYEE;
DROP TABLE TABLE_CUSTOMER;
DROP TABLE TABLE_CUSTOMER_ACCOUNT;
DROP TABLE TABLE_EMPLOYEE_POSITION;
DROP TABLE TABLE_BRANCH;